### ISSUE TITLE
improve font rendering performance

### ISSUE THREAD

**Issue by waldenn** [openglobus/openglobus#112]
From what I understand this [technique](https://stackoverflow.com/questions/25956272/better-quality-text-in-webgl) could improve text-rendering performance, especially when drawing a lot of text. 

An amazing demo [here](http://wdobbie.com/pdf/).

Other implementations:
-   https://github.com/astiopin/webgl_fonts
-   https://github.com/mapbox/tiny-sdf
-   https://github.com/dy/font-atlas-sdf

Some related discussion on caching and pooling [here](https://github.com/Linkurious/linkurious.js/issues/83) and [here](https://github.com/pixijs/pixi.js/issues/540)

**Comment by Zemledelec** [comment]
Globus allready uses sdf technique and font atlas and even billboard batching. It's in _./entity/LabelHandler.js ./utils/SDFCreator.js ./shaders/label.js_ etc. But needs new sdf creation approach, for example prerendered sdf atlases on distant server. Sdf atlas creation  is heavy algorithm for client realtime.
Undoubtedly it needs to be changed.

Tiny-sdf http://cs.brown.edu/people/pfelzens/papers/dt-final.pdf is realy interesting!

**Thoughts about performance:**
Right now you can change label text on the fly, but for real performance, it's better to create static label text line. It would be heavier to change it on the fly, but each label would represents only one billboard quad instead of several quads per letter. For example if label has "static" option true, then label is one billboard, but creation of such static billboards will take a lot of time first time I'm afraid...so will see.


**Thoughts about quality:**
New sdf source or creation.


https://github.com/openglobus/openglobus/issues

**Comment by waldenn** [comment]
Ok thanks, feel free to change the title, eg. "option to use a pre-rendered SDF font atlas".

Crazy idea: Maybe something like [GPU.js](https://github.com/gpujs/gpu.js) could be used on the client-side to "automatically compile simple JavaScript functions into shader language and run them on the GPU" one time for each set of fonts/texts and then cached. Not sure how big the output is of such a process though, if its too big it may not be feasible.

**Comment by Zemledelec** [comment]
This is beatiful!
![Roboto-Regular](https://user-images.githubusercontent.com/5452251/75606315-74705a00-5afc-11ea-889b-19a666e937de.png)
