### ISSUE TITLE
No information on how to enable 3D

### ISSUE THREAD

**Issue by kobbe** [openglobus/openglobus#264]
I almost discarded the project as not useful since I did not understand that you had to use shift key rotate the camera. Would be great if there were any clue to use the shift key.

**Comment by Zemledelec** [comment]
I can make an example, how to use keyboard handler. Do you want to disable shift key camera rotation?

**Comment by kobbe** [comment]
No, I meant mostly on https://www.openglobus.org/. How does the user understand to use the shift key?

**Comment by johnsvpaul** [comment]
when using this what needs to be put in the HTML code? It just says 'globus div' could you please show an example

**Comment by Zemledelec** [comment]
There are two ways:

1. Add hint to the homepage, because og is a library, like just code
2. Use the library control class in folder control.Control.js, for instance look ShowFps.js or DebugInfo.js

As for me I prefer the first approach, but you could propose neat hint solution with the second one.

To support the second approach the hint will be displayed in the examples, but in real life it is useless because the hint takes(little) space, and actually you can make rotation with mouse right button, or even bind your own key for this :)

P.S.
There is an example how to make custom control: http://openglobus.org/examples/customControl/customControl.html?e=1029546.13044,4620573.59013,4277154.57093&f=-0.32045,0.29540,-0.90003&u=0.02229,0.95222,0.30459

**Comment by Zemledelec** [comment]
Changed whith Alt key. Going to add a hint in the homepage.
