### ISSUE TITLE
Zooming is somehow "slow", especially on smartphone (should drop frames to keep timing if CPU is too slow)

### ISSUE THREAD

**Issue by Zemledelec** [openglobus/openglobus#269]

**Comment by der-stefan** [comment]
The problem is that the current map view still needs a lot of CPU, even when the view stands still after zooming/panning and loading the terrain data. Once there is no interaction, the rendered view does not change and should not produce heavy load.

**Comment by Zemledelec** [comment]
Reasonable issue! This is optimization task. A big step in this way is to stop passing through tile segments tree when camera is still. But whole scene have to stay in the frame loop. 

P.S.
I'm not sure It helps a lot with zooming.

**Comment by waldenn** [comment]
Hey. Just checked in here, to see if there was already an issue for something like: "sustained high CPU-load with Open Globus" and saw this issue.

I think this issue is a problem on both desktop and mobile, but on mobile its just more noticeable. I'm seeing really high CPU usage in my desktop browser (70-100%), even with no camera movement / state changes.

Two performance-related screenshots (Chrome and Firefox):
 https://ibb.co/dcJHmC4
 https://ibb.co/n1g6KCz

Seems like there should be a way to reduce the CPU load here.

Could we not just stop calling RFA when there is nothing to do? See eg. the comment here: https://stackoverflow.com/a/20659908
This would require a good, universal/automated way to keep track of this state.

**Comment by Zemledelec** [comment]
Hi @waldenn , openglobus mostly works with real-time data. I'm not sure why it takes so much CPU. Check system CPU it should b smaller (about 30%) than in the developer performance profiler. 

Of course there are many ways for optimization, and the first one is as you said prevent rendering when nothing happens, for instance, hide the tab with globus, and check the CPU it will be near zero. 

Also, it depends on how many layers you use, and the terrain, try to use EmptyTerrain provider if you don't need terrain data to display.

**Comment by waldenn** [comment]
Yes, when you hide the tab, the RFA function does not render anymore, so the CPU usage goes away.

My system CPU is very high on both Firefox (https://ibb.co/vYLPR39) and Chrome, 70-100%.
Maybe I'm the only one seeing this (Ubuntu Linux 20.04). Will check on another system when I have the possibility.

I'll check the "EmptyTerrain" option also. Thanks!

**Comment by Zemledelec** [comment]
Replaced to https://github.com/openglobus/openglobus/issues/737
