### ISSUE TITLE
The globe is partially show up, but it show full globe if rotate or drag

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#348]
The globe is partially show up, but it show full globe after rotate or drag, is this a bug?
![image](https://user-images.githubusercontent.com/8508499/129030448-70065a8b-5200-460b-9210-72a7dc36d113.png)

**Comment by pavletto** [comment]
Hi, @yeluoyunfei  What device and browser are you use? This is globe from example in repo?

**Comment by yeluoyunfei** [comment]
Hi, @pavletto  , I am using edge desktop in windows 10 . this is using the attribution example.

**Comment by Zemledelec** [comment]
Definшtely, it Looks like bug:) @yeluoyunfei is it possible to provide more information? External link would be great!

**Comment by yeluoyunfei** [comment]
@Zemledelec, This can easily repro.

**Comment by Zemledelec** [comment]
I can't catch the bug:( 
@yeluoyunfei  do you have the issue with other examples?

**Comment by Zemledelec** [comment]
Could you send a reports from here https://webglreport.com/?v=2?

**Comment by pavletto** [comment]
Maybe there are some errors in your console?

**Comment by yeluoyunfei** [comment]
tried other example, look fine. but not sure about the reason for this example. below is the recorder:
https://www.awesomescreenshot.com/video/4808624?key=9094a527b0001a109b111bc6c9e839c3
for the report:
![image](https://user-images.githubusercontent.com/8508499/129051854-eb56c046-52b3-433b-b3f2-aa3292f2e132.png)

**Comment by Zemledelec** [comment]
Webgl looks fine, thanks! Hmmm, we will try to reproduce the bug, but I have no any idea...

The shadows you see is a specular and night cities map, and there is an option for it to disable, Ill check it up, and let you know.

What kind of own things you would like to fill the globe, I could give some advise or example explanation.

Cheers!

**Comment by yeluoyunfei** [comment]
Thanks @Zemledelec ! I have disabled the sun. not sure why the specular and night cities map will be load by default. It is great that it is an option that we can disable/enable it.  I didn't find this option yet. at the first stage, I want to use my own base map and the borders can be clearly seen, like below(I can tune the background color to any color I like to increase the contrast), in future, I will add more overlay: 
![image](https://user-images.githubusercontent.com/8508499/129056777-5009882a-1aff-451d-b392-8e4ecd087b22.png)

**Comment by yeluoyunfei** [comment]
Hi, @Zemledelec.  let me know once you found it. 👍

**Comment by Zemledelec** [comment]
@yeluoyunfei
1) I'd recommend to use http://openglobus.org/examples/lighting/lighting.html control for image layers
2) Are you going to use imagery tiles(XYZ, WMS) layers?

**Comment by Zemledelec** [comment]
Check last master out, please, hope it fixes the bug.

**Comment by yeluoyunfei** [comment]
> @yeluoyunfei
> 
> 1. I'd recommend to use http://openglobus.org/examples/lighting/lighting.html control for image layers
> 2. Are you going to use imagery tiles(XYZ, WMS) layers?

@Zemledelec . Thanks! 
For #1, this looks great. Will try this.
For #2, Yes. Some of our data is  tile image data(Mercator projection). will  likely use XYZ, WMS layers. but I am not sure about the difference for XYZ, WMS. I disabled WMS in attribution example. the experience looks very similar. Can you help share some insight?

**Comment by Zemledelec** [comment]
> Yes. Some of our data is tile image data(Mercator projection). will likely use XYZ, WMS layers. but I am not sure about the difference for XYZ, WMS. I disabled WMS in attribution example. the experience looks very similar. Can you help share some insight?
>

In terms of rendering in the globe XYZ and WMS are the same, but the difference in the requests, which means that the layers are stored differently on server. In more cases XYZ data is prerendered images(tiles cache) 256x256 pixels, and WMS data is a service(last S), you could get any map images you like (image size, projection, and even styles on the fly etc.). For better understanding just take a glance in the requests in web-console. There is a good explanation https://leafletjs.com/examples/wms/wms.html.

If you want to use WMS layers you need a server (such as http://geoserver.org/ i use in my examples).
In most cases WMS is slower than XYZ, because XYZ is a imagery files cache, but you have to make the cache with gdal for example https://gdal.org/programs/gdal2tiles.html I like docker solution https://tannergeo.com/2017/10/05/Use-GDAL-With-Docker.html, because there is no version problem in the docker. On the other hand WMS is flexible service which helps you to tune your layer as you like.

P.S.
I've got your email message, and I'll answer as soon as possible!

**Comment by Zemledelec** [comment]
@yeluoyunfei, the bug solved? Could you check it up(master branch), please?

**Comment by yeluoyunfei** [comment]
Yes. this is resolved now.
