### ISSUE TITLE
Label support all Unicode? 

### ISSUE THREAD

**Issue by yeluoyunfei** [openglobus/openglobus#448]
Looks like label only support latin character(ABCabc...) now, which make it harder to build apps for different language. Support for all Unicode?

**Comment by pavletto** [comment]
If I understand correctly, it depends on the font you are using. You can generate font atlas using `msdf-bmfont` package from ttf font.
```
msdf-bmfont --reuse  -i charset.txt -m 512,512 -f json -o arial.ttf.png -s 32 -r 8 -p 1 -t msdf arial.ttf 
```

Connect your font with help next api call:
```
globe.renderer.fontAtlas.loadFont("arial", '../../fonts/', 'arial.json');
```

@Zemledelec, please, add if i missed something. Where is `npm run font` command from `package.json`?

**Comment by Zemledelec** [comment]
There is a post I ve made https://levelup.gitconnected.com/msdf-font-rendering-in-webgl-91ce192d2bec. Here you can find how to make unicode glyphs. But be sure that there is only one atlas image, because globus supports only one atlas image now. 

As @pavletto said: Here is a` charset.txt`, try to add a few unicode letters here. Also you can enlarge atlas image size to 1024 or more.
`msdf-bmfont.cmd — reuse -i .\charset.txt -m 512,512 -f json -o %1.png -s 32 -r 8 -p 1 -t msdf %1`

**Comment by Zemledelec** [comment]
@yeluoyunfei Close?

**Comment by yeluoyunfei** [comment]
@Zemledelec . Thanks for remind, I have not got a chance to check it yet. will check it soon
