### ISSUE TITLE
make ddm model

### ISSUE THREAD

**Issue by jhjojhjo** [openglobus/openglobus#454]
hi.
i will make ddm from geotiff.
1. 1st step
     convert geotiff(epsg4326) to hgt using gdal4hgt.
2. 2nd step
     convert hgt to ddm using openglobus-ddm.

what is  coordination of hgt ?
what is  coordination of ddm ?
does I need the conversion of coordination, EPSG4326->EPSG3857 ?

**Comment by Zemledelec** [comment]
...thinking

**Comment by martyrion** [comment]
Hello,

regarding this issue,  is there a way to produce our own 3d tiles from DEM in a format accepted by OG?

**Comment by Zemledelec** [comment]
Hey @martyrion! 

I forget the main question...I'm very sorry.

About DDM, I cannot recommend using ddm right now, because it is looks like deprecated I think, and I'd recommend to use MapboxTerrain provider, because it easy to make elevation tileset with gdal and rasterio (there is a docker https://github.com/openglobus/gdal-rio), from geotif and even from laz (lidar) when you include opendronemap docker in the pipeline. 

Unfortunately supporting 3DTiles is only in my dreams right now. But I suppose I'm going to start (in near future) it with simple point clouds support and then step by step going to improve compatibility.

**Comment by martyrion** [comment]
Thanks lot @Zemledelec , I will give it a shot ! By the way, if think openglobus is awesome, thanks!!

**Comment by Zemledelec** [comment]
Thanks @martyrion! Welcome to the og forum, https://groups.google.com/g/openglobus where we discuss globus engine etc.

**Comment by Zemledelec** [comment]
Answering the main question to understand ddm I'd like to refer to this answer https://github.com/openglobus/openglobus/issues/440#issuecomment-993427522
in other word ddm is a plain grid(represented as array of double values), each ddm file represents WebMercator(EPSG:3857) tile.
