### ISSUE TITLE
Entity jitters when setting location to cursor position

### ISSUE THREAD

**Issue by program-sam** [openglobus/openglobus#645]
Based on the [billBoardsOnTheGround](http://openglobus.org/examples/billboardsOnTheGround/billboardsOnTheGround.html) example I wrote code to make an entity (Polygon) track the cursor on the globe. That code looks like this:

```
this.planet.renderer.events.on(
      "mousemove",
      function (e) {
        if (that.placingObject) {
          const pos = this.getLonLatFromPixelTerrain(e);
          that.pos = pos;
          that.entity.geometry.setGeometry({
            type: "Polygon",
            coordinates: [
              [
                [ pos.lon - 0.05, pos.lat - 0.05 ],
                [ pos.lon + 0.05, pos.lat - 0.05 ],
                [ pos.lon + 0.05, pos.lat + 0.05  ],
                [ pos.lon - 0.05, pos.lat + 0.05 ],
              ],
            ],
            style: {
              fillColor: "rgba(0,0,0,0.5)",
              lineColor: "rgba(0,0,0,0.5)",
            },
          });
        }
      },
      this.planet
    );
```

The example used a point and the setLatLon function to change the location. Since this is a polygon I figured the setGeometry was the right function in this case.

This code gives me the following behaviour:

https://user-images.githubusercontent.com/75586344/223946088-54a47f90-83e9-496e-a2f7-2426ef4d1db7.mp4

Is this a bug/unavoidable/not the right way to do this?

**Comment by Zemledelec** [comment]
It happens because such a polygon is rendered each time you move it. This is not a bug. Geometry such type is a static entity, and not meant to be movable. Nevertheless, it could be improved somehow, I mean review some things in the utils/VectorTileCreator.js frame method(for instance remove _deltaTime < 0.25_ for the beginning).  Need to think about it.

If you want movable geometry, you can make an outline with Polylines, and replace geometry after the outline is moved. Also, it is more complicated to create your own geometry on the GeoTexture2d framebuffer, but it needs to do some things, like your own shaders, and stitching GeoTextures2d...so no out-of-the-box solution.

**Comment by program-sam** [comment]
Ok I understand. Geometry, being a static entity, will always lead to this effect because it gets redrawn every time it is changed rather than 'moved'. Unless the VectorTileCreator is optimized even more so that you don't notice it being redrawn (just removing the deltaTime < 0.25 sadly isn't a quick fix).

Indeed Polylines seem to move much more smoothly, but they also seem to have some unexpected behavior when dragging them up close. I'll see if I can open an issue about that as well.

I also noticed GeoImages would be a usable alternative to draw a simple rectangle based on corner coordinates. I'll play around with that as well

Thanks for the clarification!
