### ISSUE TITLE
[Feature] When will library support 3d model?

### ISSUE THREAD

**Issue by RakeshShrestha** [openglobus/openglobus#708]
Maybe openwebglobe, cesiumjs all supports 3d structure

**Comment by pavletto** [comment]
Hello @RakeshShrestha. You can use `geoobject` to visualize 3d objects in openglobus. not so long time ago i added support .obj format to openglobus.  We have example in our repo `examples/geoObject`. We will add examples and tutorials on how to use this tool later

**Comment by RakeshShrestha** [comment]
Thanks for the replay. I checked the sample. Ayway obj format you support currently I am not digging into it but there I saw interesting files fish.json and fish.png . Is The fish.json is this based on the tool https://www.blender.org/

On extra thing is it possbile to call esri layers similar to https://developers.arcgis.com/cesiumjs/scenes/ . If possible example also might be good. Not to support or ignore esri presense means the library will also be ignored for many good use cases

**Comment by Zemledelec** [comment]
> On extra thing is it possbile to call esri layers similar to https://developers.arcgis.com/cesiumjs/scenes/ . If possible example also might be good. Not to support or ignore esri presense means the library will also be ignored for many good use cases

Hi, @RakeshShrestha! I agree, that openglobus have to support as many external sources as possible. This is why openglobus is designed to be changed by adding new features with the control (plugin) system. In the same way, openglobus doesn't try to grasp everything, instead, it focused on providing basic things as easily as possible. For instance, openglobus support all kinds of imagery layers such as XYZ, WMS, and CanvasTiles (where you could draw any map you need) and Vector layers such as KML. In case of imagery layer it's easy to provide any ESRI imagery layer, based on WebMercator, or EPSG4326 projection. Here is a few examples:
https://openglobus.org/examples/mars/mars.html
https://openglobus.org/examples/layerSwitcher/layerSwitcher.html

As for terrain(elevation) data openglobus also provides an interface for the visualization of regular grid data. Right now it supports Mapbox rgba terrain data source (sorry my Mapbox key is expired I can't show an example), but it's quite easy to create even your own elevation data source, from real GeoTif. I'm going to make some examples in the near future.

>Thanks for the replay. I checked the sample. Ayway obj format you support currently I am not digging into it but there I saw interesting files fish.json and fish.png . Is The fish.json is this based on the tool https://www.blender.org/

fish.json is the same as .obj but was exported with blender plugin https://github.com/openglobus/openglobus/blob/master/blender.py. This is the same as you export obj from blender. I suggest the py script make deprecated because we can work with simple meshes obj files.

FYI @pavletto

**Comment by RakeshShrestha** [comment]
Great I agree. Thanks for the reply and library. The reason I liked your library is very thin. 

I am going to use your library in Android and Window Appx WebView. Once I finished the task and release I will send you the link also.

**Comment by Zemledelec** [comment]
Thank you @RakeshShrestha! Would be very interesting to see what you do, and we will be very pleased to help with any related questions. You are welcome!
