### ISSUE TITLE
 CORS issue with the official examples in Firefox 120.0

### ISSUE THREAD

**Issue by majidfer** [openglobus/openglobus#789]
I've noticed CORS issue with the official examples in Firefox 120.0:

![cors issue openglobus](https://github.com/openglobus/openglobus/assets/7728543/314bda9c-cfba-4c72-9908-f9aecaef849d)

**Comment by Zemledelec** [comment]
Hi @majidfer! In this case, red CORS errors mean that the elevation data file (*.ddm) doesn't exist on the server. For instance, for the red cors url: a.srtm3.openglobus.org/**19**/267580/275452.ddm means that this file doesn't exist, because the maximal zoom level for openglobus terrain provider(*.ddm) format is 14! The same issue applies to lower zoom levels for open water, such as oceans and seas around even for lower zoom levels.
It's useful when you have availability data for various zoom levels, which is often a situation for MapboxTerrain providers.

P.S.
Also, I updated  openglobus server, now it's only https requests available. If no terrain is visible try to clean the browser cache.

**Comment by majidfer** [comment]
Hi @Zemledelec! Thanks for your response! It really helped me understand the mechanics behind the scenes.

I have another question, if you don't mind. I've successfully integrated OpenGlobus into my React project and managed to display the component. However, when I zoom in, the names of countries or other areas don't show up as they do in the official example. Please take a look at these screenshots for comparison:

![image](https://github.com/openglobus/openglobus/assets/7728543/1a6cd0f3-b4e6-4a0c-bb65-65b12ed67eae)

My component:

![image](https://github.com/openglobus/openglobus/assets/7728543/a3c4112f-2fe0-4147-bc51-901937265b18)

I'd greatly appreciate any suggestions you might have. Thank you in advance.

**Comment by Zemledelec** [comment]
For proper using globus in react check this https://github.com/openglobus/og-examples/blob/renew_examples/components/globus/globusreact.jsx

This week we try to publish openglobus-react repository for react apps. Which is mostly based on the Context and Ref in the brunch I mentioned above.

About labels:

1. Check labels font is loaded, filter network with font face name like qrial, by default. It must be loaded arial.ttf.png and arial.json.
2. If you use another face, try to find your name instead of arial. I suppose it's 404.
3. You have to set `fontsSrc` parameter in `Globus` constructor, the path to *.json and *.ttf.png font files location. https://openglobus.org/examples/examples/fonts/fonts.html

**Comment by majidfer** [comment]
Thanks for your response; I really appreciate it!
